exclude_paths:
  - 'config/**/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'app/channels/application_cable/channel.rb'
  - 'app/channels/application_cable/connection.rb'
  - 'app/domains/ai_devs_3/**/*'

detectors:
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 10
  UncommunicativeModuleName:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  DataClump:
    enabled: false
  BooleanParameter:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 10
  ControlParameter:
    enabled: false
  LongParameterList:
    max_params: 10
  TooManyConstants:
    max_constants: 10

directories:
  'app/controllers**':
    InstanceVariableAssumption:
      enabled: false
  '**/utils**':
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  '**/**/utils**':
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  '**/services**':
    UtilityFunction:
      enabled: false
  '**/**/helpers**':
    UtilityFunction:
      enabled: false
  'app/helpers**':
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  'app/api/rupert/helpers**':
    FeatureEnvy:
      enabled: false

