services:
  db:
    container_name: rupert_prod_db
    image: ankane/pgvector:v0.5.1
    ports:
      - "5433:5433"
    expose:
      - "5433"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - rupert_prod:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vector"]
  rupert:
    container_name: rupert_prod
    image: ghcr.io/pankarol88/rupert:latest
    command: sh -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 20240"
    ports:
      - "20240:20240"
    expose:
      - "20240"
    environment:
      - RAILS_ENV=production
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  rupert_prod:
